### PR TITLE
add support latest CryptoSwift version

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**

### CODE REVIEW

**Comment by hboon** [comment]
Why is this PR needed?

**Comment by vladyslav-iosdev** [comment]
> Why is this PR needed?

It needs to resolve conflicts beetwen dependencies, several dependencies are using different versions of `CryptoSwift`

**Comment by hboon** [comment]
Do you mean to get the AlphaWallet project to build with Xcode 12?

**Comment by vladyslav-iosdev** [comment]
> Do you mean to get the AlphaWallet project to build with Xcode 12?

and https://github.com/AlphaWallet/latest-keystore-snapshot/pull/1#issuecomment-721542948 also requires this changes

**Comment by hboon** [comment]
Ok. Is this good to merge?

**Comment by hboon** [comment]
Travis is failing

**Pull request closed without merging**
